---
title: "normScore: a package for assessing normalization in proteomics data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r  include = F, message = F, error=F, warning=F}
####------------       BASIC CODE FOR BUILDING THE PACKAGE      ------------####

# Change branch in Bioconductor from main to devel
# BiocManager::install(version = "devel")
# BiocManager::version()
# BiocManager::valid()


# Initial commands...
usethis::proj_get()
usethis::use_description()
usethis::use_namespace()
usethis::use_roxygen_md()
usethis::use_testthat()
usethis::use_news_md()
usethis::use_vignette("normScore-intro")

# Creating 
usethis::use_r("utils")
usethis::use_r("normScore")
usethis::use_r("simulateData")


# Building 
roxygen2::roxygenise() # man folder


# Checking 
devtools::document()
devtools::check()
# BiocCheck::BiocCheck() # execution at Devel from BiorManager()


# Installing 
devtools::install()
```


# normScore

*normScore* is an R package for evaluating and ranking normalization methods in proteomics data based on a composite score that integrates multiple performance metrics


